name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker Image
        run: |
          docker build -t kurkasebastian/projektarbeit:latest .
          docker push kurkasebastian/projektarbeit:latest
         # echo "${{ secrets.CI_CD_GITHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
         # docker tag projektarbeit ${{ secrets.DOCKER_USERNAME }}/projektarbeit:latest
  
#env:
#  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#  CI_CD_GITHUB_TOKEN: ${{secrets.CI_CD_GITHUB_TOKEN}}

