name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker Image
        run: |
          docker build -t projektarbeit .
          docker tag projektarbeit ${{ secrets.DOCKER_USERNAME }}/projektarbeit:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/projektarbeit:latest

  
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
